<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-12-22 04:25

$extensionPath = t3lib_extMgm::extPath('languagevisibility');
return array(
	'tx_languagevisibility_behooks' => $extensionPath . 'class.tx_languagevisibility_behooks.php',
	'tx_languagevisibility_beservices' => $extensionPath . 'class.tx_languagevisibility_beservices.php',
	'tx_languagevisibility_feservices' => $extensionPath . 'class.tx_languagevisibility_feservices.php',
	'tx_languagevisibility_cachemanager' => $extensionPath . 'classes/class.tx_languagevisibility_cacheManager.php',
	'tx_languagevisibility_celement' => $extensionPath . 'classes/class.tx_languagevisibility_celement.php',
	'tx_languagevisibility_element' => $extensionPath . 'classes/class.tx_languagevisibility_element.php',
	'tx_languagevisibility_elementfactory' => $extensionPath . 'classes/class.tx_languagevisibility_elementFactory.php',
	'tx_languagevisibility_fceelement' => $extensionPath . 'classes/class.tx_languagevisibility_fceelement.php',
	'tx_languagevisibility_fceoverlayelement' => $extensionPath . 'classes/class.tx_languagevisibility_fceoverlayelement.php',
	'tx_languagevisibility_language' => $extensionPath . 'classes/class.tx_languagevisibility_language.php',
	'tx_languagevisibility_languagerepository' => $extensionPath . 'classes/class.tx_languagevisibility_languagerepository.php',
	'tx_languagevisibility_pageelement' => $extensionPath . 'classes/class.tx_languagevisibility_pageelement.php',
	'tx_languagevisibility_recordelement' => $extensionPath . 'classes/class.tx_languagevisibility_recordelement.php',
	'tx_languagevisibility_ttnewselement' => $extensionPath . 'classes/class.tx_languagevisibility_ttnewselement.php',
	'tx_languagevisibility_visibility' => $extensionPath . 'classes/class.tx_languagevisibility_visibility.php',
	'tx_languagevisibility_visibilityservice' => $extensionPath . 'classes/class.tx_languagevisibility_visibilityService.php',
	'tx_languagevisibility_daocommon' => $extensionPath . 'classes/dao/class.tx_languagevisibility_daocommon.php',
	'tx_languagevisibility_daocommon_stub' => $extensionPath . 'classes/dao/class.tx_languagevisibility_daocommon_stub.php',
	'tx_languagevisibility_invalidrowexception' => $extensionPath . 'classes/exceptions/class.tx_languagevisibility_InvalidRowException.php',
	'tx_languagevisibility_modfunc1' => $extensionPath . 'modfunc1/class.tx_languagevisibility_modfunc1.php',
	'tx_languagevisibility_beuser' => $extensionPath . 'patch/lib/class.tx_languagevisibility_beUser.php',
	'tx_languagevisibility_commandmap' => $extensionPath . 'patch/lib/class.tx_languagevisibility_commandMap.php',
	'tx_languagevisibility_databasetestcase' => $extensionPath . 'tests/tx_languagevisibility_databaseTestcase.php',
);
?>